### ISSUE TITLE
Stormwater infrastructure

### ISSUE THREAD

**Issue by baerbock** [impiaaa/SV-OSM#5]
Hi Spencer,

I would be interested in the stormwater infrastructure. Where may I get the data from to run `stormwater.py`?

**Comment by impiaaa** [comment]
[San Jose official data download](https://www.sanjoseca.gov/your-government/departments-offices/public-works/resources/gis-data-downloads). Looks like the link has changed from the one in the README. stormwater.py is only needed for operation with OpenStreetMap, usually the .shp files should just be loaded as a layer in your preferred GIS suite.
